Web/HikePals.Web/Controllers/AboutController.cs
namespace HikePals.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net.Mail;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;

    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return this.View();
        }
    }
}

Web/HikePals.Web/Controllers/ContactsController.cs
namespace HikePals.Web.Controllers
{
    using HikePals.Data.Models;
    using HikePals.Services.Data;
    using HikePals.Web.ViewModels.Contacts;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class ContactsController : BaseController
    {
        private readonly IMailService mailService;
        private readonly UserManager<ApplicationUser> userManager;

        public ContactsController(IMailService mailService, UserManager<ApplicationUser> userManager)
        {
            this.mailService = mailService;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Index(ContactFormInputViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            this.mailService.SendContactFormEmailAsync(input.Email, input.Subject, input.Content, input.Name);
            return this.View("ThankYou");
        }
    }
}

Web/HikePals.Web/Controllers/EventsController.cs
namespace HikePals.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using HikePals.Common;
    using HikePals.Data.Models;
    using HikePals.Services.Data;
    using HikePals.Services.Data.Contracts;
    using HikePals.Web.ViewModels.Chat;
    using HikePals.Web.ViewModels.Events;
    using HikePals.Web.ViewModels.Trips;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class EventsController : BaseController
    {
        private readonly ITransportService transportService;
        private readonly IEventsService eventsService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IChatService chatService;

        public EventsController(ITransportService transportService, IEventsService eventsService, UserManager<ApplicationUser> userManager, IChatService chatService)
        {
            this.transportService = transportService;
            this.eventsService = eventsService;
            this.userManager = userManager;
            this.chatService = chatService;
        }

        [HttpGet]
        public IActionResult Create(int id)
        {
            var model = this.eventsService.MapTripData(id);
            model.TransportItems = this.transportService.GetAllTransportTypes();
            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateEventInputViewModel input)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var eventId = await this.eventsService.CreateNewEvent(input, user.Id);

            this.TempData["Message"] = "You have sucessully added a hiking event!";

            return this.RedirectToAction(nameof(this.GetById), new { id = eventId });
        }

        [HttpGet]
        public async Task<IActionResult> GetById(int id)
        {
            var model = this.eventsService.GetById<EventViewModel>(id);

            if (model == null)
            {
                return this.RedirectToAction("NotFoundError", "Error");
            }

            var user = await this.userManager.GetUserAsync(this.User);
            model.UserId = user.Id;

            return this.View(model);
        }

        [AllowAnonymous]
        public IActionResult All()
        {
            var model = new AllEventAsListViewModel();
            model.Events = this.eventsService.GetAll<SingleEventListViewModel>();

            return this.View(model);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
           var model = this.eventsService.GetById<EditEventViewModel>(id);

           if (model == null)
           {
                return this.RedirectToAction("NotFoundError", "Error");
           }

           model.TransportItems = this.transportService.GetAllTransportTypes();
           return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditEventViewModel input)
        {
            await this.eventsService.UpdateAsync(input);
            var eventId = input.Id;

            return this.RedirectToAction(nameof(this.GetById), new { id = eventId });
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (!this.eventsService.Exists(id))
            {
                return this.RedirectToAction("NotFoundError", "Error");
            }

            await this.eventsService.DeleteAsync(id);

            return this.RedirectToAction(nameof(this.All));
        }

        public async Task<IActionResult> RequestJoinEvent(int id)
        {
           var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
           var eventId = id;
           var isAdmin = this.User.IsInRole("Administrator");

           try
           {
              await this.eventsService.RequestJoinEvent(eventId, userId, isAdmin);
           }
           catch (Exception ex)
           {
               this.ModelState.AddModelError(string.Empty, ex.Message);
               return this.RedirectToAction("GetbyId", new { id = eventId });
           }

           return this.RedirectToAction("GetbyId", new { id = eventId });
        }

        public async Task<IActionResult> ApproveJoinEvent(int id, string participantId)
        {
            var eventId = id;

            try
            {
                await this.eventsService.ApproveJoinRequest(participantId, eventId);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.RedirectToAction("GetbyId", new { id = eventId });
            }

             // Get previous page Url address
            var referer = this.Request
                .Headers["Referer"]
                .ToString();

            return this.Redirect(referer);
        }

        public async Task<IActionResult> Leave(int id, string participantId)
        {
            try
            {
                await this.eventsService.LeaveEvent(participantId, id);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.RedirectToAction("GetbyId", new { id = id });
            }

            return this.RedirectToAction("GetbyId", new { id = id });
        }

        public async Task<IActionResult> UndoJoinRequest(int id)
        {
            var userId = this.User
                .FindFirstValue(ClaimTypes.NameIdentifier);

            try
            {
                await this.eventsService.UndoJoinRequest(userId, id);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.RedirectToAction("GetbyId", new { id = id });
            }

            return this.RedirectToAction("GetbyId", new { id = id });
        }
    }
}

Web/HikePals.Web/Controllers/TripsController.cs
namespace HikePals.Web.Controllers
{
    using System;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using HikePals.Data.Models;
    using HikePals.Services.Data;
    using HikePals.Services.Data.Contracts;
    using HikePals.Web.ViewModels.Trips;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class TripsController : Controller
    {
        private readonly ICitiesService citiesService;
        private readonly ICategoriesService categoriesService;
        private readonly ITripsService tripsService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment environment;

        public TripsController(
            ICitiesService citiesService,
            ICountriesService countryService,
            ICategoriesService categoriesService,
            ITransportService transportService,
            ITripsService tripsService,
            UserManager<ApplicationUser> userManager,
            IWebHostEnvironment environment,
            IRatingsService ratingsService)
        {
            this.citiesService = citiesService;
            this.categoriesService = categoriesService;
            this.tripsService = tripsService;
            this.userManager = userManager;
            this.environment = environment;
        }

        [Authorize]
        public IActionResult CreateTrip()
        {
            var viewModel = new CreateTripInputViewModel();

            viewModel.CityItems = this.citiesService.GetAllCities();
            viewModel.CategoryItems = this.categoriesService.GetAllCategoriesAsListItems();

            return this.View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreateTrip(CreateTripInputViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.CategoryItems = this.categoriesService.GetAllCategoriesAsListItems();
                input.CityItems = this.citiesService.GetAllCities();
                return this.View(input);
            }

            var imagesDirPath = $"{this.environment.WebRootPath}\\images";

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            try
            {
                await this.tripsService.Create(input, userId, imagesDirPath);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                input.CategoryItems = this.categoriesService.GetAllCategoriesAsListItems();
                input.CityItems = this.citiesService.GetAllCities();
                return this.View(input);
            }

            this.TempData["Message"] = "You have sucessully added a hiking route!";

            return this.RedirectToAction("All");
        }

        public IActionResult All([FromQuery] AllTripsViewModel query)
        {
            var model = this.tripsService
                .GetAll(
                query.SearchTerm,
                query.Category,
                query.Sorting,
                query.CurrentPage,
                AllTripsViewModel.TripPerPage);

            var categories = this.categoriesService.All();
            model.Categories = categories;

            return this.View(model);
        }

        public IActionResult ByCategory(int id)
        {
            var model = this.tripsService.GetAllByCategory<AllTripsViewModel>(id);
            return this.View("All", model);
        }

        [Authorize]
        public async Task<IActionResult> GetById(int id)
        {
            var model = this.tripsService.GetById<TripViewModel>(id);

            if (this.ModelBinderFactory == null)
            {
                return this.RedirectToAction("NotFoundError", "Error");
            }

            var userId = this.User
                .FindFirst(ClaimTypes.NameIdentifier)
                .Value;

            model.UserId = userId;

            return this.View(model);
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            var model = this.tripsService.GetById<CreateTripInputViewModel>(id);

            model.CityItems = this.citiesService.GetAllCities();
            model.CategoryItems = this.categoriesService.GetAllCategoriesAsListItems();

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CreateTripInputViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.CategoryItems = this.categoriesService.GetAllCategoriesAsListItems();
                input.CityItems = this.citiesService.GetAllCities();

                this.View(input);
            }

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var imagesDirPath = $"{this.environment.WebRootPath}\\images";

            await this.tripsService.UpdateAsync(input, userId, imagesDirPath);

            var model = this.tripsService.GetById<TripViewModel>(input.Id);

            if (model == null)
            {
                return this.RedirectToAction("NotFoundError", "Error");
            }

            return this.RedirectToAction(nameof(this.GetById), new { id = input.Id });
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            if (!this.tripsService.Exists(id))
            {
               return this.RedirectToAction("NotFoundError", "Error");
            }

            await this.tripsService.DeleteAsync(id);
            return this.RedirectToAction("All");
        }
    }
}

Web/HikePals.Web/Views/Shared/_AllEventsPartial.cshtml
@model HikePals.Web.ViewModels.Events.AllEventAsListViewModel



<div class="row">

    @foreach (var hike in Model.Events)
    {
        <div class="card col-md-4 m-5">
            <div class="embed-responsive embed-responsive-4by3">
                <a asp-controller="Events" asp-action="GetById" asp-route-id="@hike.Id">
                    <img class="card-img-top img-responsive embed-responsive-item" src="@hike.ImageUrl" alt="@hike.Title" style="margin:10px; margin-left:0">
                </a>
            </div>

            <div class="card-body">
                <a asp-controller="Events" asp-action="GetById" asp-route-id="@hike.Id"><h5 class="card-title md-1">@hike.Title</h5></a>
                <p class="card-text">Start: @hike.StartTime.Date.ToString("g", System.Globalization.CultureInfo.InvariantCulture)</p>
                <span class="card-text"><i class="far fa-clock"></i> @hike.TripDuration.TotalHours.ToString("0.0") h |</span>
                <span class="card-text"><i class="fas fa-road"></i> @hike.TripDistance km |</span>
                <span class="card-text"><i class="fas fa-user-friends"></i> @hike.CurrentNumberParticipants/@hike.MaxGroupSize </span>
                <p>

                    <a asp-controller="Events" asp-action="GetById" asp-route-id="@hike.Id" class="btn btn-primary">Read more</a>
                </p>

            </div>
        </div>
    }

</div>

Web/HikePals.Web/Views/Shared/_AllTripsPartial.cshtml
@model HikePals.Web.ViewModels.Trips.AllTripsViewModel


<div class="row">
    @foreach (var trip in this.Model.Trips)
    {
        <div class="card col-md-4 m-5">
            <div class="embed-responsive embed-responsive-4by3">
                <a asp-controller="Trips" asp-action="GetById" asp-route-id="@trip.Id">
                    <img class="card-img-top img-responsive embed-responsive-item" src="@trip.ImageUrl" alt="@trip.Title" style="margin: 10px; margin-left:0">
                </a>
            </div>

            <div class="card-body">
                <a asp-controller="Trips" asp-action="GetById" asp-route-id="@trip.Id"><h5 class="card-title md-1">@trip.Title</h5></a>
                <div class="container" style="margin-bottom: 15px">

                    @if (trip.AverageRating != 0 && trip.AverageRating > 0.4)
                    {
                        <span data-vote="1"><i id="star" class="fas fa-star checked"></i></span>
                    }
                    else
                    {
                        <span data-vote="1"><i id="star" class="fas fa-star"></i></span>
                    }
                    @if (trip.AverageRating != 0 && trip.AverageRating > 1.4)
                    {
                        <span data-vote="2"><i id="star" class="fas fa-star checked"></i></span>
                    }
                    else
                    {
                        <span data-vote="2"><i class="fas fa-star"></i></span>
                    }
                    @if (trip.AverageRating != 0 && trip.AverageRating > 2.4)
                    {
                        <span data-vote="3"><i id="star" class="fas fa-star checked"></i></span>
                    }
                    else
                    {
                        <span data-vote="3"><i class="fas fa-star"></i></span>
                    }
                    @if (trip.AverageRating != 0 && trip.AverageRating > 3.4)
                    {
                        <span data-vote="4"><i id="star" class="fas fa-star checked"></i></span>
                    }
                    else
                    {
                        <span data-vote="4"><i class="fas fa-star"></i></span>
                    }
                    @if (trip.AverageRating >= 4.5)
                    {
                        <span data-vote="5"><i id="star" class="fas fa-star checked"></i></span>
                    }
                    else
                    {
                        <span data-vote="5"><i class="fas fa-star"></i></span>
                    }
                    <span id="averageRating">@trip.AverageRating.ToString("0.0")</span> <span>/ 5</span>

                </div>
                @if (this.User.Identity.IsAuthenticated)
                {
                    <a asp-controller="Trips" asp-action="GetById" asp-route-id="@trip.Id" class="btn btn-primary">Read more</a>
                }
                else
                {
                    <a class="btn btn-dark  btn-pill" asp-area="Identity" asp-page="/Account/Register">Read more</a>

                }
            </div>
        </div>
    }

</div>

Web/HikePals.Web/Views/Shared/_CreateTripPartial.cshtml
@model HikePals.Web.ViewModels.Trips.CreateTripInputViewModel

<form method="post" class="col-md-6 offset-md-3" enctype="multipart/form-data">

    <div class="form-group">
        <label asp-for="Title">Name</label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>

    </div>

    <div class="form-group">
        <label asp-for="Description">Description</label>
        <textarea asp-for="Description" class="form-control" rows="6"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="LocationName">Point of Interest / Destination name</label>
        <input asp-for="LocationName" class="form-control" />
        <span asp-validation-for="LocationName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="CategoryId">Destination Category</label>
        <select asp-for="CategoryId" class="form-control custom-select" asp-items="Model.CategoryItems">
            <option value="">Choose Destination Category</option>
        </select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="CityId">City</label>
        <select asp-for="CityId" class="form-control" asp-items="Model.CityItems">
            <option value="">Choose а City</option>
        </select>
        <span asp-validation-for="CityId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Distance">Distance (km)</label>
        <input asp-for="Distance" class="form-control" />
        <span asp-validation-for="Distance" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Duration">Approximate duration (hours)</label>
        <input asp-for="Duration" class="form-control" />
        <span asp-validation-for="Duration" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="TripImage"></label>
        <input asp-for="TripImage" class="form-control" />
        <span asp-validation-for="TripImage" class="text-danger"></span>
    </div>

    <input type="submit" value="Submit" class="btn-block" />

</form>

Web/HikePals.Web/Views/Shared/_Layout.cshtml
@using HikePals.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" />
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/lazy.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #106eea">
            <div class="container">
                <a class="navbar-brand d-flex align-items-center" asp-area="" asp-controller="Home" asp-action="Index"><img class="card-img" id="logo" src="~/images/logo-cropped.png" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown-1" aria-controls="navbarNavDropdown-1"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse text-center" id="navbarNavDropdown-1">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Events" asp-action="All">Join Live Event</a>
                            </li>
                        }
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#a" id="navbarDropdownMenuLink" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false"> Hike Routes Gallery</a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-area="" asp-controller="Trips" asp-action="All">All</a>
                                @if (this.User.Identity.IsAuthenticated)
                                {
                                    <a class="dropdown-item" asp-controller="Trips" asp-action="CreateTrip">Create</a>
                                    <a class="dropdown-item" asp-controller="Categories" asp-action="Index">By Category</a>
                                }
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Contacts" asp-action="Index">Contacts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="About" asp-action="Index">About</a>
                        </li>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container mt-5">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted mt-5">

        <div class="container" style="text-align:center">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script type="text/javascript" src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/HikePals.Web/Views/Shared/_TripEditPartial.cshtml
@model HikePals.Web.ViewModels.Trips.EditTripViewModel


<h1>
    Edit
</h1>
    <form method="post" class="col-md-6 offset-md-3" enctype="multipart/form-data">

        <div class="form-group">
            <label asp-for="Title">Name</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>

        </div>

        <div class="form-group">
            <label asp-for="@Model.Description">Description</label>
            <textarea asp-for="@Model.Description" class="form-control" rows="6"></textarea>
            <span asp-validation-for="@Model.Description" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="@Model.LocationName">Destination / Point of Interest</label>
            <input asp-for="@Model.LocationName" class="form-control" />
            <span asp-validation-for="@Model.LocationName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="TypeOfDestinationId">Destination Category</label>
            <select asp-for="TypeOfDestinationId" class="form-control" asp-items="@Model.CategoriesItems" class="custom-select">
                <option value="">Choose Destination Category</option>
            </select>
            <span asp-validation-for="TypeOfDestinationId" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="TypeOfDestinationId">City</label>
            <select asp-for="CityId" class="form-control" asp-items="Model.CityItems">
                <option value="">Choose City</option>
            </select>
            <span asp-validation-for="TypeOfDestinationId" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Distance">Distance</label>
            <input asp-for="Distance" class="form-control" />
            <span asp-validation-for="Distance" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Duration">Duration</label>
            <input asp-for="Duration" class="form-control" />
            <span asp-validation-for="Duration" class="text-danger"></span>
        </div>

        <div> </div>
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Submit" class="btn-block" />

    </form>

Web/HikePals.Web/Views/Shared/_TripViewPartial.cshtml
@model HikePals.Web.ViewModels.Trips.TripViewModel

<div class="card col-12">
    <div class="card-body">

        <div class="card-text"><h5>@Model.LocationName</h5></div>
        <div class="d-flex flex-row align-items-md-start">
            <div class="p-2">@Model.LocationCityName <i class="fas fa-city"></i> |</div>
            <div class="p-2">Distance - @Model.Distance km <i class="fas fa-road"></i> |</div>
            <div class="p-2">Duration - @Model.Duration.TotalHours.ToString("0.00") h <i class="far fa-clock"></i></div>
        </div>

        <div class="container" style="margin-bottom: 15px">

            @if (Model.AverageRating != 0 && Model.AverageRating > 0.4)
            {
                <span data-vote="1"><i id="star" class="fas fa-star checked"></i></span>
            }
            else
            {
                <span data-vote="1"><i id="star" class="fas fa-star"></i></span>
            }
            @if (Model.AverageRating != 0 && Model.AverageRating > 1.4)
            {
                <span data-vote="2"><i id="star" class="fas fa-star checked"></i></span>
            }
            else
            {
                <span data-vote="2"><i class="fas fa-star"></i></span>
            }
            @if (Model.AverageRating != 0 && Model.AverageRating > 2.4)
            {
                <span data-vote="3"><i id="star" class="fas fa-star checked"></i></span>
            }
            else
            {
                <span data-vote="3"><i class="fas fa-star"></i></span>
            }
            @if (Model.AverageRating != 0 && Model.AverageRating > 3.4)
            {
                <span data-vote="4"><i id="star" class="fas fa-star checked"></i></span>
            }
            else
            {
                <span data-vote="4"><i class="fas fa-star"></i></span>
            }
            @if (Model.AverageRating >= 4.5)
            {
                <span data-vote="5"><i id="star" class="fas fa-star checked"></i></span>
            }
            else
            {
                <span data-vote="5"><i class="fas fa-star"></i></span>
            }
            <span id="averageRating">@Model.AverageRating.ToString("0.0")</span> <span>/ 5</span>
        </div>
    </div>
    <img src="@Model.ImageUrl" alt="" />
    <div class="card-body">
        <p class="card-text">@Model.Description</p>
    </div>
</div>