Web/HikePals.Web/Areas/Administration/Controllers/TripsController.cs
namespace HikePals.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using HikePals.Services.Data;
    using HikePals.Services.Data.Contracts;
    using HikePals.Web.ViewModels.Trips;
    using Microsoft.AspNetCore.Mvc;

    public class TripsController : AdministrationController
    {
        private readonly ITripsService tripsService;
        private readonly ICitiesService citiesService;
        private readonly ICategoriesService categoriesService;

        public TripsController(ITripsService tripsService, ICitiesService citiesService, ICategoriesService categoriesService)
        {
            this.tripsService = tripsService;
            this.citiesService = citiesService;
            this.categoriesService = categoriesService;
        }

        // GET: Administration/Trips
        public IActionResult Index()
        {
            var model = this.tripsService.GetAllWithDeleted();

            return this.View(model);
        }

        // GET: Administration/Trips/Details/5
        public IActionResult Details(int id)
        {
            var trip = this.tripsService.GetByIdWithDeleted<TripViewModel>(id);
            if (trip == null)
            {
                return this.NotFound();
            }

            return this.View(trip);
        }

        // GET: Administration/Trips/Create
        public IActionResult Create()
        {
            return this.RedirectToAction("Create", nameof(Web.Controllers.TripsController));
        }

        // GET: Administration/Trips/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (!this.tripsService.Exists(id))
            {
                return this.NotFound();
            }

            await this.tripsService.DeleteAsync(id);
            return this.RedirectToAction(nameof(this.Index));
        }

        public async Task<IActionResult> Restore(int id)
        {
            await this.tripsService.RestoreAsync(id);
            return this.RedirectToAction(nameof(this.Index));
        }
    }
}

Web/HikePals.Web/Controllers/CategoriesController.cs
namespace HikePals.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using HikePals.Services.Data.Contracts;
    using HikePals.Web.ViewModels.Categories;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class CategoriesController : BaseController
    {
        private ICategoriesService categoriesService;

        public CategoriesController(ICategoriesService categoriesService)
        {
            this.categoriesService = categoriesService;
        }

        public IActionResult Index()
        {
            var model = new AllCategoriesViewModel()
            {
                Categories = this.categoriesService.GetAllCategories(),
            };
            return this.View(model);
        }
    }
}

Web/HikePals.Web/Controllers/EventsController.cs
namespace HikePals.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using HikePals.Common;
    using HikePals.Data.Models;
    using HikePals.Services.Data;
    using HikePals.Services.Data.Contracts;
    using HikePals.Web.ViewModels.Chat;
    using HikePals.Web.ViewModels.Events;
    using HikePals.Web.ViewModels.Trips;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class EventsController : BaseController
    {
        private readonly ITransportService transportService;
        private readonly IEventsService eventsService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IChatService chatService;

        public EventsController(ITransportService transportService, IEventsService eventsService, UserManager<ApplicationUser> userManager, IChatService chatService)
        {
            this.transportService = transportService;
            this.eventsService = eventsService;
            this.userManager = userManager;
            this.chatService = chatService;
        }

        [HttpGet]
        public IActionResult Create(int id)
        {
            var model = this.eventsService.MapTripData(id);
            model.TransportItems = this.transportService.GetAllTransportTypes();
            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateEventInputViewModel input)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var eventId = await this.eventsService.CreateNewEvent(input, user.Id);

            this.TempData["Message"] = "You have sucessully added a hiking event!";

            return this.RedirectToAction(nameof(this.GetById), new { id = eventId });
        }

        [HttpGet]
        public async Task<IActionResult> GetById(int id)
        {
            var model = this.eventsService.GetById<EventViewModel>(id);

            if (model == null)
            {
                return this.RedirectToAction("NotFoundError", "Error");
            }

            var user = await this.userManager.GetUserAsync(this.User);
            model.UserId = user.Id;

            return this.View(model);
        }

        [AllowAnonymous]
        public IActionResult All()
        {
            var model = new AllEventAsListViewModel();
            model.Events = this.eventsService.GetAll<SingleEventListViewModel>();

            return this.View(model);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
           var model = this.eventsService.GetById<EditEventViewModel>(id);

           if (model == null)
           {
                return this.RedirectToAction("NotFoundError", "Error");
           }

           model.TransportItems = this.transportService.GetAllTransportTypes();
           return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditEventViewModel input)
        {
            await this.eventsService.UpdateAsync(input);
            var eventId = input.Id;

            return this.RedirectToAction(nameof(this.GetById), new { id = eventId });
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (!this.eventsService.Exists(id))
            {
                return this.RedirectToAction("NotFoundError", "Error");
            }

            await this.eventsService.DeleteAsync(id);

            return this.RedirectToAction(nameof(this.All));
        }

        public async Task<IActionResult> RequestJoinEvent(int id)
        {
           var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
           var eventId = id;
           var isAdmin = this.User.IsInRole("Administrator");

           try
           {
              await this.eventsService.RequestJoinEvent(eventId, userId, isAdmin);
           }
           catch (Exception ex)
           {
               this.ModelState.AddModelError(string.Empty, ex.Message);
               return this.RedirectToAction("GetbyId", new { id = eventId });
           }

           return this.RedirectToAction("GetbyId", new { id = eventId });
        }

        public async Task<IActionResult> ApproveJoinEvent(int id, string participantId)
        {
            var eventId = id;

            try
            {
                await this.eventsService.ApproveJoinRequest(participantId, eventId);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.RedirectToAction("GetbyId", new { id = eventId });
            }

             // Get previous page Url address
            var referer = this.Request
                .Headers["Referer"]
                .ToString();

            return this.Redirect(referer);
        }

        public async Task<IActionResult> Leave(int id, string participantId)
        {
            try
            {
                await this.eventsService.LeaveEvent(participantId, id);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.RedirectToAction("GetbyId", new { id = id });
            }

            return this.RedirectToAction("GetbyId", new { id = id });
        }

        public async Task<IActionResult> UndoJoinRequest(int id)
        {
            var userId = this.User
                .FindFirstValue(ClaimTypes.NameIdentifier);

            try
            {
                await this.eventsService.UndoJoinRequest(userId, id);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.RedirectToAction("GetbyId", new { id = id });
            }

            return this.RedirectToAction("GetbyId", new { id = id });
        }
    }
}

Web/HikePals.Web/Controllers/TripsController.cs
namespace HikePals.Web.Controllers
{
    using System;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using HikePals.Data.Models;
    using HikePals.Services.Data;
    using HikePals.Services.Data.Contracts;
    using HikePals.Web.ViewModels.Trips;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class TripsController : Controller
    {
        private readonly ICitiesService citiesService;
        private readonly ICategoriesService categoriesService;
        private readonly ITripsService tripsService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment environment;

        public TripsController(
            ICitiesService citiesService,
            ICountriesService countryService,
            ICategoriesService categoriesService,
            ITransportService transportService,
            ITripsService tripsService,
            UserManager<ApplicationUser> userManager,
            IWebHostEnvironment environment,
            IRatingsService ratingsService)
        {
            this.citiesService = citiesService;
            this.categoriesService = categoriesService;
            this.tripsService = tripsService;
            this.userManager = userManager;
            this.environment = environment;
        }

        [Authorize]
        public IActionResult CreateTrip()
        {
            var viewModel = new CreateTripInputViewModel();

            viewModel.CityItems = this.citiesService.GetAllCities();
            viewModel.CategoryItems = this.categoriesService.GetAllCategoriesAsListItems();

            return this.View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreateTrip(CreateTripInputViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.CategoryItems = this.categoriesService.GetAllCategoriesAsListItems();
                input.CityItems = this.citiesService.GetAllCities();
                return this.View(input);
            }

            var imagesDirPath = $"{this.environment.WebRootPath}\\images";

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            try
            {
                await this.tripsService.Create(input, userId, imagesDirPath);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                input.CategoryItems = this.categoriesService.GetAllCategoriesAsListItems();
                input.CityItems = this.citiesService.GetAllCities();
                return this.View(input);
            }

            this.TempData["Message"] = "You have sucessully added a hiking route!";

            return this.RedirectToAction("All");
        }

        public IActionResult All([FromQuery] AllTripsViewModel query)
        {
            var model = this.tripsService
                .GetAll(
                query.SearchTerm,
                query.Category,
                query.Sorting,
                query.CurrentPage,
                AllTripsViewModel.TripPerPage);

            var categories = this.categoriesService.All();
            model.Categories = categories;

            return this.View(model);
        }

        public IActionResult ByCategory(int id)
        {
            var model = this.tripsService.GetAllByCategory<AllTripsViewModel>(id);
            return this.View("All", model);
        }

        [Authorize]
        public async Task<IActionResult> GetById(int id)
        {
            var model = this.tripsService.GetById<TripViewModel>(id);

            if (this.ModelBinderFactory == null)
            {
                return this.RedirectToAction("NotFoundError", "Error");
            }

            var userId = this.User
                .FindFirst(ClaimTypes.NameIdentifier)
                .Value;

            model.UserId = userId;

            return this.View(model);
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            var model = this.tripsService.GetById<CreateTripInputViewModel>(id);

            model.CityItems = this.citiesService.GetAllCities();
            model.CategoryItems = this.categoriesService.GetAllCategoriesAsListItems();

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CreateTripInputViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.CategoryItems = this.categoriesService.GetAllCategoriesAsListItems();
                input.CityItems = this.citiesService.GetAllCities();

                this.View(input);
            }

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var imagesDirPath = $"{this.environment.WebRootPath}\\images";

            await this.tripsService.UpdateAsync(input, userId, imagesDirPath);

            var model = this.tripsService.GetById<TripViewModel>(input.Id);

            if (model == null)
            {
                return this.RedirectToAction("NotFoundError", "Error");
            }

            return this.RedirectToAction(nameof(this.GetById), new { id = input.Id });
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            if (!this.tripsService.Exists(id))
            {
               return this.RedirectToAction("NotFoundError", "Error");
            }

            await this.tripsService.DeleteAsync(id);
            return this.RedirectToAction("All");
        }
    }
}

Web/HikePals.Web/Views/Trips/All.cshtml
@model HikePals.Web.ViewModels.Trips.AllTripsViewModel

<head>
    <link href="~/css/AllTrips/index.css" rel="stylesheet" />
</head>
@if (this.TempData.ContainsKey("Message"))
{
    <div class="alert alert-dismissible alert-success" role="alert">@this.TempData["Message"] <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button></div>
}

<h1 class="text-center mt-2">Find a hike route that suits you best!</h1>

<div class="row justify-content-center mt-5">
    <div class="col-md-4 mb-4 text-center">
    <a class="btn btn-outline-primary justify-content-center d-flex my-auto"  asp-area="" asp-controller="Trips" asp-action="CreateTrip">Create you own Hike Route</a>
    </div>
</div>

<form id="form" method="get">
    <div class="row">
        <div class="form-group col-md-4">
            <div class="form-group">
                <label asp-for="Category"></label>
                <select id="category" asp-for="Category" class="form-control">
                    <option value="">All</option>

                    @foreach (var category in Model.Categories)
                    {
                        <option value="@category">@category</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group col-md-4">
            <label asp-for="SearchTerm"></label>
            <input asp-for="SearchTerm" class="form-control" placeholder="Vitosha, Svoge, Kom, etc...">
        </div>

        <div class="form-group col-md-4">
                    <div class="form-group">
                        <label asp-for="Sorting"></label>
                        <select id="sortBy" asp-for="Sorting" class="form-control">
                            <option value="0" selected>Category</option>
                            <option value="1">Location</option>
                            <option value="2">Date added</option>
                            <option value="3">Rating</option>
                        </select>
                    </div>
                </div>
    </div>
</form>


@{
    int previousPage;
    if (Model.CurrentPage == 1)
    {
        previousPage = Model.CurrentPage;
    }
    else
    {
        previousPage = Model.CurrentPage - 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalTripsCount / HikePals.Web.ViewModels.Trips.AllTripsViewModel.TripPerPage);
}
<div class="row mb-8 d-flex justify-content-center">
    <div class="col-md-4 mb-4 text-center">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)" 
           asp-controller="Trips" 
           asp-action="All" 
           asp-route-currentPage="@previousPage"
           asp-route-sorting="@Model.Sorting"
           asp-route-category="@Model.Category"
           asp-route-searchTerm="@Model.SearchTerm">
            <<

        </a>
        <p class="d-inline mb-6 margin-bottom: auto">... @Model.CurrentPage ...</p>
        <a class="btn btn-primary @(Model.CurrentPage == maxPage ? "disabled" : string.Empty) " data-maxpage="@maxPage"
           asp-controller="Trips"
           asp-action="All"
           asp-route-currentPage="@(Model.CurrentPage + 1)"
           asp-route-sorting="@Model.Sorting"
           asp-route-category="@Model.Category"
           asp-route-searchTerm="@Model.SearchTerm">
            >>

        </a>
    </div>

</div>
<div class="row justify-content-around">
    @foreach (var trip in this.Model.Trips)
    {
        <div class="card col-md-3 m-1">
            <div class="embed-responsive embed-responsive-4by3">
                <a asp-controller="Trips" asp-action="GetById" asp-route-id="@trip.Id">
                    <img class="card-img-top img-responsive embed-responsive-item" src="@trip.ImageUrl" alt="@trip.Title" style="margin: 10px; margin-left:0">
                </a>
            </div>

            <div class="card-body">
                <a asp-controller="Trips" asp-action="GetById" asp-route-id="@trip.Id"><h5 class="card-title md-1">@trip.Title</h5></a>
                <div class="container" style="margin-bottom: 15px">

                    @if (trip.AverageRating != 0 && trip.AverageRating > 0.4)
                    {
                        <span data-vote="1"><i id="star" class="fas fa-star checked"></i></span>
                    }
                    else
                    {
                        <span data-vote="1"><i id="star" class="fas fa-star"></i></span>
                    }
                    @if (trip.AverageRating != 0 && trip.AverageRating > 1.4)
                    {
                        <span data-vote="2"><i id="star" class="fas fa-star checked"></i></span>
                    }
                    else
                    {
                        <span data-vote="2"><i class="fas fa-star"></i></span>
                    }
                    @if (trip.AverageRating != 0 && trip.AverageRating > 2.4)
                    {
                        <span data-vote="3"><i id="star" class="fas fa-star checked"></i></span>
                    }
                    else
                    {
                        <span data-vote="3"><i class="fas fa-star"></i></span>
                    }
                    @if (trip.AverageRating != 0 && trip.AverageRating > 3.4)
                    {
                        <span data-vote="4"><i id="star" class="fas fa-star checked"></i></span>
                    }
                    else
                    {
                        <span data-vote="4"><i class="fas fa-star"></i></span>
                    }
                    @if (trip.AverageRating >= 4.5)
                    {
                        <span data-vote="5"><i id="star" class="fas fa-star checked"></i></span>
                    }
                    else
                    {
                        <span data-vote="5"><i class="fas fa-star"></i></span>
                    }
                    <span id="averageRating">@trip.AverageRating.ToString("0.0")</span> <span>/ 5</span>

                </div>
                    <div class="text-center">
                @if (this.User.IsInRole("User") || this.User.IsInRole("Administrator"))
                {
                        <a class="btn btn-primary " asp-controller="Trips" asp-action="GetById" asp-route-id="@trip.Id" >Read more</a>
                }
                else
                {
                        <a class="btn btn-primary" asp-area="Identity" asp-page="/Account/Register">Read more</a>
                }
                    </div>
            </div>
        </div>
    }

</div>

@section Scripts{ 
<script>
    $('#category, #sortBy').change(function () {

        let formData = $('#form').serialize();
        let currentUrl = 'https://localhost:44319/Trips/All?';
        let redirectTo = currentUrl + formData;

        window.location.href = redirectTo;
    });
</script>
} 

Web/HikePals.Web/Views/Trips/CreateTrip.cshtml
@model HikePals.Web.ViewModels.Trips.CreateTripInputViewModel

<h1 class="offset-md-3">Create a new trip!</h1>
@{await Html.RenderPartialAsync("_CreateTripPartial", this.Model);}

Web/HikePals.Web/Views/Trips/Edit.cshtml
@model HikePals.Web.ViewModels.Trips.CreateTripInputViewModel

@{await Html.RenderPartialAsync("_CreateTripPartial", this.Model);}


@*<form method="post" class="col-md-6 offset-md-3" enctype="multipart/form-data">

        <div class="form-group">
            <label asp-for="Title">Name</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>

        </div>

        <div class="form-group">
            <label asp-for="@Model.Description">Description</label>
            <textarea asp-for="@Model.Description" class="form-control" rows="6"></textarea>
            <span asp-validation-for="@Model.Description" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="@Model.LocationName">Destination / Point of Interest</label>
            <input asp-for="@Model.LocationName" class="form-control" />
            <span asp-validation-for="@Model.LocationName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="TypeOfDestinationId">Destination Category</label>
            <select asp-for="TypeOfDestinationId" asp-items="@Model.CategoriesItems" class="custom-select form-control">
                <option value="">Choose Destination Category</option>
            </select>
            <span asp-validation-for="TypeOfDestinationId" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="TypeOfDestinationId">City</label>
            <select asp-for="CityId" class="form-control" asp-items="Model.CityItems">
                <option value="">Choose City</option>
            </select>
            <span asp-validation-for="TypeOfDestinationId" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Distance">Distance (in km)</label>
            <input asp-for="Distance" class="form-control" />
            <span asp-validation-for="Distance" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Duration">Duration</label>
            <input asp-for="Duration" class="form-control" />
            <span asp-validation-for="Duration" class="text-danger"></span>
        </div>

        <div > </div>
        <input type="hidden" asp-for="Id"/>
        <input type="submit" value="Submit" class="btn-block" />

    </form>*@

Web/HikePals.Web/Views/Trips/GetById.cshtml
@model HikePals.Web.ViewModels.Trips.TripViewModel
@{ this.ViewData["Title"] = Model.Title; }


<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
        <li class="breadcrumb-item"><a asp-controller="Trips" asp-action="All">Hike Routes Gallery</a></li>
        <li class="breadcrumb-item active" aria-current="page">@Model.Title</li>
    </ol>
</nav>

<div class=role aria-label="Basic example" style="vertical-align:middle; text-align: center; margin-left:10px; margin-right:10px; ">
    @if (this.User.IsInRole("Administrator") || Model.UserId == Model.CreatedById)
	{
    <a type="button" class="btn btn-primary" style="vertical-align:middle; text-align: center; margin-left:10px; margin-right:10px; margin-bottom: 10px;" asp-area="" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
    <a type="button" class="btn btn-danger" style="vertical-align:middle; text-align: center; margin-left:10px; margin-right:10px; margin-bottom: 10px;" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>		 
	}
    <a type="button" class="btn btn-success" style="vertical-align:middle; text-align: center; margin-left:10px; margin-right:10px; margin-bottom: 10px;" asp-controller="Events" asp-action="Create" asp-route-id="@Model.Id">Create Event</a>
</div>


<div class="row " style="margin-right: 0px;margin-left: 0px;">
    <div class="col-2 border">
        <ul class="nav flex-column">
            <li class="nav-item ">
                <a class="nav-link active" asp-controller="Categories" asp-action="Index">Categories</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Cities</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link disabled" href="#">Points Of Interest</a>
            </li>
        </ul>
    </div>
    <div class="col-8">
        @{await Html.RenderPartialAsync("_TripViewPartial", this.Model);}
    </div>

</div>

<form method="post" id="antiForgeryForm"></form>
@section Scripts{
    <script>
    $("span[data-vote]").each(function (el) {
        $(this).click(function () {


            var value = $(this).attr("data-vote");
            var rating = parseInt(value);
            var tripId = @Model.Id;
            var antiForgeryToken = $('#antiForgeryForm input[name=__RequestVerificationToken]').val();
            var data = { value: rating, tripId: tripId };

            $.ajax({
                type: "POST",
                url: "/api/Ratings",
                data: JSON.stringify(data),
                dataType: 'json',
                contentType: 'application/json',
                headers: {
                    'X-CSRF-TOKEN': antiForgeryToken
                },
                success: function (data) {
                    $('#averageRating').text(data.averageRating);
                },

              
            });
        })
    })
    </script>
}